### ISSUE TITLE
Problem with illuminate/http version definition

### ISSUE THREAD

**Issue by peter279k** [PHPWatch/Laravel-Fast404#1]
As title, the `illuminate/http` version definitions are `^5.5 || ^6.0 || ^7.0` on `composer.json`.

It seems that `illuminate/http` version can require `php-7.0` version at least, but this package requires `php-7.4` version at least.

It will be failed when developers install this package because of the PHP version requirements.

To resolve this issue, I think it should let package require `php-7.x` version at least.

**Comment by Ayesh** [comment]
Hi @peter279k - thanks for yet another nice issue in this project as well. 
In [`src/Fast404Middleware.php` file](https://github.com/PHPWatch/Laravel-Fast404/blob/v1.0.0/src/Fast404Middleware.php#L13-L15), it uses [typed properties](https://php.watch/versions/7.4/typed-properties) that are only available in PHP 7.4 and later. While we can make it compatible with older versions by removing the property types, I think it makes more sense to keep it, given that only PHP 7.3 is the only active PHP versions that we leave out, and even that version loses its official active support in ~3 months.

**Comment by peter279k** [comment]
I also recommend using the `illuminate/http` versions are `^6.0 || ^7.0`.

And let package require `php-7.3` version at least :).
